version: '3.8'

services:
  # 1. Database Postgres
  postgres-db:
    image: postgres:15-alpine
    container_name: techvalley-postgres
    environment:
      POSTGRES_USER: techvalley_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: techvalley_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - techvalley-net
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: techvalley-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@techvalley.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 2. Auth & Gateway Service (Spring Boot)
  auth-gateway-service:
    build:
      context: .
      dockerfile: auth-gateway-service/Dockerfile
    container_name: auth-gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/techvalley_db
      - SPRING_DATASOURCE_USERNAME=techvalley_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 3. Core Cloud Monitor Service (Spring Boot)
  cloud-monitor-service:
    build:
      context: .
      dockerfile: cloud-monitor-service/Dockerfile
    container_name: cloud-monitor-service
    ports:
      - "8086:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/techvalley_db
      - SPRING_DATASOURCE_USERNAME=techvalley_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 4. Instance Microservice (Phan Thị Cẩm Ly)
  instance-service:
    build:
      context: .
      dockerfile: instance-service/Dockerfile
    container_name: instance-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/techvalley_db
      - SPRING_DATASOURCE_USERNAME=techvalley_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 5. Client Microservice (Trịnh Lương Việt)
  client-service:
    build:
      context: .
      dockerfile: client-service/Dockerfile
    container_name: client-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/techvalley_db
      - SPRING_DATASOURCE_USERNAME=techvalley_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 6. Monitoring Microservice (Thân Đức Minh)
  monitoring-service:
    build:
      context: .
      dockerfile: monitoring-service/Dockerfile
    container_name: monitoring-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/techvalley_db
      - SPRING_DATASOURCE_USERNAME=techvalley_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 7. Alert Microservice (Lê Thị Thuý Hằng)
  alert-service:
    build:
      context: .
      dockerfile: alert-service/Dockerfile
    container_name: alert-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/techvalley_db
      - SPRING_DATASOURCE_USERNAME=techvalley_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - postgres-db
    networks:
      - techvalley-net

  # 8. LLM Service (Spring Boot)
  llm-service:
    build:
      context: .
      dockerfile: llm-service/Dockerfile
    container_name: llm-service
    ports:
      - "8085:8082"
    networks:
      - techvalley-net

  # 9. Frontend Demo (Nginx Web Server)
  frontend-demo:
    build: ./frontend-demo
    container_name: frontend-demo
    ports:
      - "80:80"
      - "3000:80"
      - "8088:80"
    depends_on:
      - auth-gateway-service
    networks:
      - techvalley-net

networks:
  techvalley-net:
    driver: bridge

volumes:
  pgdata: