server:
  port: 8082

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:postgresql://postgres-client:5432/techvalley_client
    username: techvalley_admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
instance-service:
  base-url: ${INSTANCE_SERVICE_URL:http://localhost:8081}
alert-service:
  base-url: ${ALERT_SERVICE_URL:http://localhost:8084}

springdoc:
  packagesToScan: com.techvalley.monitor.client
  swagger-ui:
    path: /swagger-ui.html
    url: /docs/client-api-docs
    config-url: /docs/client-config
    
jwt:
  secret: 3DqK8sXv2NfL9pWa5RmTy7HuBcEeGhJk

internal:
  api-key: ${INTERNAL_API_KEY:changeme-internal-key-please-override}
