server:
  port: 8083

spring:
  application:
    name: monitoring-service
  
instance-service:
  base-url: ${INSTANCE_SERVICE_URL:http://localhost:8081}
alert-service:
  base-url: ${ALERT_SERVICE_URL:http://localhost:8084}
client-service:
  base-url: ${CLIENT_SERVICE_URL:http://localhost:8082}
  
springdoc:
  packagesToScan: com.techvalley.monitor.monitoring

jwt:
  secret: 3DqK8sXv2NfL9pWa5RmTy7HuBcEeGhJk
internal:
  api-key: ${INTERNAL_API_KEY:changeme-internal-key-please-override}
